require('plugs')
require('keymaps')
require('configs')

-- Plugins config
require('plugins/lualine')
require('plugins/lsp')
require('plugins/cmp')
require('plugins/treesitter')
require('plugins/telescope')
require('plugins/comments')
require('plugins/vimtex')
require('plugins/code_runner')
require('plugins/nvimtree')
-- require('plugins/luasnip')
