#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

monitor1=$(xrandr | grep " connected" | head -n 1 | awk '{print $1}')
if [[ "$(xrandr | grep " connected" | wc -l)" -eq "2" ]]; then
    monitor2=$(xrandr | grep " connected" | tail -n 1 | awk '{print $1}')
    bspc monitor $monitor1 -d 1 2 3
    bspc monitor $monitor2 -d 4 5 6
else
    bspc monitor $monitor1 -d 1 2 3
fi


bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#f8f8f8"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# rules
bspc rule -a "VirtualBox Manager" state=floating center=true
bspc rule -a "Org.gnome.Nautilus" state=floating center=true
bspc rule -a "URxvt" state=floating center=true
bspc rule -a "Yad" state=floating center=true
bspc rule -a "Eog" state=floating center=true
bspc rule -a "Rcommander" state=floating center=true
bspc rule -a "R_x11" state=floating center=true
bspc rule -a "com-cburch-logisim-Main" state=floating center=true
bspc rule -a "Nm-connection-editor" state=floating center=true
bspc rule -a "ensamblador-Ensamblador" state=tile

# wallpaper
sleep 0.1
feh --bg-scale --randomize ./.dotfiles/wallpapers/* &

# cursor
xsetroot -cursor_name left_ptr &

sleep 0.1
sudo chown vieites:vieites "/sys/class/leds/apple::kbd_backlight/brightness"
sudo chown vieites:vieites "/sys/class/backlight/acpi_video0/brightness"

# autostart
if [ $(hostname) = "macbookpro" ]; then
    ~/.mac.sh &
else
    ~/.screen_layout.sh &
fi
~/.screensaver.sh &
compton -b &
flameshot &
pgrep -u $USER -x nm-applet > /dev/null || (nm-applet &)
ibus-daemon &
$HOME/.config/polybar/launch.sh &

dunst -conf $HOME/.config/dunst/dunstrc &
killall battery.sh > /dev/null
$HOME/.config/dunst/scripts/battery.sh
