#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#f8f8f8"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a "VirtualBox Manager" state=floating center=true
bspc rule -a "Org.gnome.Nautilus" state=floating center=true

# wallpaper
sleep 0.1
feh --bg-scale ./.dotfiles/wallpapers/bg_1.jpg &

# cursor
xsetroot -cursor_name left_ptr &

sleep 0.1
sudo chown vieites:vieites "/sys/class/leds/apple::kbd_backlight/brightness"
sudo chown vieites:vieites "/sys/class/backlight/acpi_video0/brightness"

# autostart
if [ $(hostname) = "macbookpro" ]; then
    ~/.mac.sh &
else
    ~/.screen_layout.sh &
fi
~/.screensaver.sh &
compton -b &
flameshot &
pgrep -u $USER -x nm-applet > /dev/null || (nm-applet &)
ibus-daemon &
$HOME/.config/polybar/launch.sh &

dunst -conf $HOME/.config/dunst/dunstrc &
killall battery.sh > /dev/null
$HOME/.config/dunst/scripts/battery.sh
