#!/bin/bash

if [[ $(bspc query -N -d focused | wc -l) == 0 && $(bspc query -D -m focused | wc -l) > 3 ]]; then
  current_desktop=$(bspc query -D -d focused)
    bspc desktop ${current_desktop} --remove
    $HOME/.config/bspwm/scripts/renumber_desktops
fi
